# Generated by Django 5.1.2 on 2024-11-10 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_portal', to='core.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Настройка портала',
                'verbose_name_plural': 'Настройки портала',
                'ordering': ['portal', 'pk'],
            },
        ),
    ]
