# Generated by Django 5.1.2 on 2024-11-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsportal',
            name='cost_in_deal_code',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля себестоимость из задач в сделках. Множественное поле.', max_length=30, verbose_name='Код поля себестоимость из задач'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='cost_in_task_code',
            field=models.CharField(default='UF_AUTO_643983320441', max_length=30, verbose_name='Код поля себестоимость в задачах'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='ids_tasks_in_deal_code',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля ID задач в сделках. Множественное поле.', max_length=30, verbose_name='Код поля ID задач'),
        ),
        migrations.AddField(
            model_name='settingsportal',
            name='links_tasks_in_deal_code',
            field=models.CharField(default='UF_CRM_0000000000', help_text='Код поля ссылки на задачи в сделках. Множественное поле.', max_length=30, verbose_name='Код поля ссылки на задачи'),
        ),
    ]
